sudo: required	
dist: trusty	
	
#install google chrome, using addons	
addons:	
  apt:	
    sources:	
      - google-chrome	
    packages:	
      - google-chrome-stable

language: node_js

cache:
  yarn: true
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '9'
  - '8'
  - '6'

before_script:	
  - export DISPLAY=:99.0	
  - sh -e /etc/init.d/xvfb start	
  - npm install --quiet -g gulp-cli

script: gulp test:ci

after_success:
  - gulp coveralls
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
